apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigate
  labels:
    app: apigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigate
  template:
    metadata:
      labels:
        app: apigate
    spec:
      containers:
        - name: apigate
          image: username/apigate:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
